# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[(1, b'Cool Event'), (2, b'Super Cool Event')], max_length=2, verbose_name='Event Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='coolevent',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='coolevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='coolevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coolevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supercoolevent',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='supercoolevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='supercoolevent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supercoolevent',
            name='user',
        ),
        migrations.AddField(
            model_name='coolevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supercoolevent',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.Event'),
            preserve_default=False,
        ),
    ]
